In [1]:
import numpy as np

In [2]:
x = [1,2,3.2,5,6,8]

In [3]:
a = np.array(x)

In [4]:
a

array([1. , 2. , 3.2, 5. , 6. , 8. ])

In [5]:
print(a*3)

[ 3.   6.   9.6 15.  18.  24. ]


In [6]:
y = a*3

In [7]:
y

array([ 3. ,  6. ,  9.6, 15. , 18. , 24. ])

In [8]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
x = np.arange(3.2)
y = np.arange(0.1,1.2,0.1)
print(x)
print(y)

[0. 1. 2. 3.]
[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1]


In [10]:
x = np.arange(4.5)

In [11]:
x

array([0., 1., 2., 3., 4.])

In [12]:
y = np.arange(0.1,5.0,0.2)
y

array([0.1, 0.3, 0.5, 0.7, 0.9, 1.1, 1.3, 1.5, 1.7, 1.9, 2.1, 2.3, 2.5,
       2.7, 2.9, 3.1, 3.3, 3.5, 3.7, 3.9, 4.1, 4.3, 4.5, 4.7, 4.9])

In [13]:
a = np.array([1,2,3,4])
b = np.array([[1,1],[2,2],[3,3]])

In [14]:
print(a)
print(b)

[1 2 3 4]
[[1 1]
 [2 2]
 [3 3]]


In [15]:
np.shape(a)

(4,)

In [16]:
np.shape(b)

(3, 2)

In [17]:
print(b[0])
print(b[0][1])
print(a[1:3])

[1 1]
1
[2 3]


In [18]:
a[2:4]

array([3, 4])

In [19]:
#generating random numbers

a = np.random.randn(10,5)

In [20]:
print(a)

[[-1.01544743  0.77971537 -1.56925817 -1.03696438  1.1278842 ]
 [ 1.7299226  -0.43849835  0.68707675 -1.20206418 -0.17012071]
 [-1.08290561  0.60772749 -0.24579069  0.11935147 -0.34456908]
 [ 0.1785915   0.01304536  0.04667433 -0.42987634 -0.32893385]
 [ 0.39633354 -3.16101639  0.18604974  0.68746135 -0.4313531 ]
 [ 0.52341721 -0.97123978 -0.97945425 -1.36803831  0.65040253]
 [-1.33476719  1.60327794  0.66148633 -0.17939303  0.02489489]
 [-0.88307813 -1.54674954  0.44565611  0.85317705 -2.05725417]
 [ 1.0914794   0.3697168   0.08480181 -1.13047662  1.06053726]
 [-0.02221313 -1.43647296 -1.12388284 -1.04043507  0.0541982 ]]


In [21]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

print("Slice")
print(a[1:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Slice
[[4 5 6]
 [7 8 9]]


In [22]:
a = np.array([[1,2,3],[3,4,5],[5,6,7]])
print('Our array is:')
print(a)
print('\n')

print('The items in the second column are:')
print(a[...,1])
print('\n')

print('The items in the row are:')
print(a[1,...])
print('\n')

print('Items column 1 onwards are:')
print(a[...,1:])

Our array is:
[[1 2 3]
 [3 4 5]
 [5 6 7]]


The items in the second column are:
[2 4 6]


The items in the row are:
[3 4 5]


Items column 1 onwards are:
[[2 3]
 [4 5]
 [6 7]]
